# Generated by Django 5.0.6 on 2024-07-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
